"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os
from datetime import timedelta

from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-dev-secret-key-change-this"
)

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost"
    ).split(",")
    if host.strip()
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",
    "django_filters",
    "rest_framework_simplejwt.token_blacklist",

    # Project apps
    "accounts",
    "cases",
    "documents",
    "investigations",
    "complaints",
    "legal",
    "audit",
    "evidence",
    "ai",
    "search",
    "dashboard",
    "notifications",
   


]




MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS must be before CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]




ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"




TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]




# SQLite is perfectly fine for the current showcase/demo stage.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "sddms",
        "USER": "postgres",
        "PASSWORD": "Sunilsahu15",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}



AUTH_USER_MODEL = "accounts.User"




AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]




LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True




STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"




MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"




# Showcase/development:
# Emails will appear in the terminal instead of being sent.

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)




REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),

    # Clean API responses for showcase/frontend development
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.PageNumberPagination"
    ),

    "PAGE_SIZE": 20,
}




SIMPLE_JWT = {
    # Token lifetime
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    # Refresh token rotation
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    # Update last_login after successful authentication
    "UPDATE_LAST_LOGIN": True,

    # Authorization header
    "AUTH_HEADER_TYPES": ("Bearer",),

    # JWT signing
    "SIGNING_KEY": SECRET_KEY,
    "ALGORITHM": "HS256",
}



# React/Vite frontend during development/showcase.

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",

    # Vite default ports
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]




SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = False

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"

SECURE_REFERRER_POLICY = "same-origin"



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



DOCUMENT_SIGNING_PRIVATE_KEY = os.environ.get(
    "DOCUMENT_SIGNING_PRIVATE_KEY",
    ""
)

DOCUMENT_SIGNING_PUBLIC_KEY = os.environ.get(
    "DOCUMENT_SIGNING_PUBLIC_KEY",
    ""
)

if not DOCUMENT_SIGNING_PRIVATE_KEY:
    private_key_path = BASE_DIR / "keys" / "document_private.pem"

    if private_key_path.exists():
        DOCUMENT_SIGNING_PRIVATE_KEY = private_key_path.read_text()

if not DOCUMENT_SIGNING_PUBLIC_KEY:
    public_key_path = BASE_DIR / "keys" / "document_public.pem"

    if public_key_path.exists():
        DOCUMENT_SIGNING_PUBLIC_KEY = public_key_path.read_text()


GEMINI_API_KEY = os.environ.get(
    "GEMINI_API_KEY",
    "",
)

GEMINI_MODEL = os.environ.get(
    "GEMINI_MODEL",
    "ggemini-3.8-flash",
)